title: Zihan Zhang
description: My Personal Blog
author: 张子涵
logo: /landbuland.github.io/static/img/IMG_6183 (2).JPG
github: https://github.com/landbuland
about: Keep smiling.

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-145837376-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown

gems: [jekyll-paginate, jekyll-gist]

