title: Zihan Zhang
description: My Blog
author: Zihan Zhang (In Chinese: 张子涵)
logo: /landbuland.github.io/static/img/smile.jpeg
github: https://github.com/landbuland
about: Keep smiling.

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-145837376-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown

gems: [jekyll-paginate, jekyll-gist]

